# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "15ec214b-b921-4f36-8117-d3556382640f"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later


lane :GITTriggered do
  setup_jenkins(result_bundle: false)
end


lane :beta do
  increment_build_number(
    xcodeproj: "ios/friedensflotte.xcodeproj"
  )
  setup_jenkins(result_bundle: false)
  gym(
    scheme: "friedensflotte",
    workspace: 'ios/friedensflotte.xcworkspace',
    export_method: "app-store"
  )
  testflight(
    username: "habi1986@gmx.at",
    #jenkins needs this:
    team_id: "118550562",
    team_name: "Stefanie Habersatter",
    skip_waiting_for_build_processing: true
  )
end

lane :deliverDONTEXECUTE do
    #versionsnummer incrementen?
    increment_build_number(
      xcodeproj: "ios/friedensflotte.xcodeproj"
    )
  gym(
    scheme: "friedensflotte",
    workspace: 'ios/friedensflotte.xcworkspace',
    export_method: "app-store"
  )
  # upload to Testflight - brauch ma ned - aba braucht jenkins de daten XD?:
  testflight(
    username: "habi1986@gmx.at",
    #jenkins braucht des:
    team_id: "118550562",
    team_name: "Stefanie Habersatter",
    skip_waiting_for_build_processing: true
  )
  deliver # nur deliver? nix gym ? increment versions nummer?
end


lane :screenshots do
  snapshot(
      workspace: 'ios/friedensflotte.xcworkspace',
      scheme: 'friedensflotte',
      languages: ['de-DE'],
      devices: ["iPhone 6"],
  )
end


lane :framedScreenshots do
  snapshot(
      workspace: 'ios/friedensflotte.xcworkspace',
      scheme: 'friedensflotte',
      languages: ['de-DE'],
      devices: ["iPhone 6"],
  )
  frameit(white: true)
  #deliver
end







lane :archivBuild do
 gym(
  archive_path: "output/friedensflotte 2017-07-26 15.22.40.xcarchive"
 )

end