# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "15ec214b-b921-4f36-8117-d3556382640f"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later


lane :beta do
  # build your iOS app
  #increment_build_number //error :/
  # snapshot
  gym(
    scheme: "friedensflotte",
    #project: 'ios/friedensflotte.xcodeproj',
    workspace: 'ios/friedensflotte.xcworkspace',
    export_method: "app-store"
  )
  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

end

lane :screenshots do
  snapshot(
      workspace: 'ios/friedensflotte.xcworkspace',
      scheme: 'friedensflotte',
      #languages: ['de-DE'],
      devices: ["iPhone 6"],
  )
  #frameit(white: true, path: './fastlane/screenshots')
  #frameit(white: true)

  #deliver
end

lane :test do
    scan(device: "iPhone 5s")
end

lane :frame do
  frameit(white: true, path: './fastlane/screenshots')
end